browserify "src/deutils.cluster.js" -o "./dist/deutils.cluster.br.js"
browserify "src/deutils.core.js" -o "./dist/deutils.core.br.js"
browserify "src/deutils.network.js" -o "./dist/deutils.network.br.js"
browserify "src/deutils.time.js" -o "./dist/deutils.time.br.js"
browserify "src/deutils.wait.js" -o "./dist/deutils.wait.br.js"
